# Generated by Django 2.2.16 on 2022-06-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220603_1114'),
    ]

    operations = [
        migrations.RenameField('Follow', 'author', 'following'),
    ]
